AcerCMS/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcerCMS.Models;

namespace AcerCMS.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            var model = new List<News>();
            using (var db = new AcerCmsEntities())
            {
                model = db.News.OrderByDescending(o=> o.UpdateDate).ToList();
            }
            return View(model);
        }

        public ActionResult ReadNews(int id)
        {
            using (var db = new AcerCmsEntities())
            {
                var model = db.News.Find(id);

                if (model == null)
                    return HttpNotFound("Haber Bulunamadı!");

                return View(model);
            }
        }

    }
}

AcerCMS/Controllers/PictureController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcerCMS.Models;

namespace AcerCMS.Controllers
{
    public class PictureController : Controller
    {
        // GET: Picture
        public ActionResult Index()
        {
            var model = new List<Picture>();
            using (var db = new AcerCmsEntities())
            {
                model = db.Pictures.ToList();
            }
            return View(model);
        }
    }
}

AcerCMS/Views/Shared/_FooterPartial.cshtml
<!--Footer-->
<hr />
<footer>
    <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
</footer>

AcerCMS/Views/Shared/_HeaderPartial.cshtml
<!--Header-->
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home"></i> Ana Sayfa</a></li>                
                <li>@Html.ActionLink("Hakkımızda", "About", "Home")</li>
                <li>@Html.ActionLink("İletişim", "Contact", "Home")</li>
                <li>@Html.ActionLink("Haberler ve Duyurular", "Index", "News")</li>
                <li>@Html.ActionLink("Haber Ekle", "AddSomeNews", "Home")</li>
                <li>@Html.ActionLink("Resimler", "Index", "Picture")</li>
            </ul>
        </div>
    </div>
</div>

AcerCMS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <!--TODO: Change To Bundle-->
    <link href="~/Content/font-awesome.min.css" rel="stylesheet" />
    @RenderSection("styles", required: false)
</head>
<body>
    @Html.Partial("_HeaderPartial")

    @RenderSection("slides", required: false)

    <div class="container body-content">
        @RenderBody()

        @Html.Partial("_FooterPartial")
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>